
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://wenjay.mysql:3306/dxz_platform_demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&tinyInt1isBit=false

test:
  activate: activate-dev
  myEnv: ENC(91qL9aVp0EYMHPEu3nrZe/2h3K1jk3NVy4kF0M/KzdI=)
