# 加密配置
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES #加密方式
    password: a#Je&lJYj^b3I4Up #加密密码

#App服务配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson: # Jackson配置
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  messages:
    encoding: UTF-8
    basename: i18n.messages

# baomidou-mybatisplus 配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  #mapper扫描
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-handlers-package: com.wenjay.framework.data.mysql.handler
  #实体扫描，多个package用逗号或者分号分隔
  #type-aliases-package com.baomidou.springboot.entity
  #枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性
  type-enums-package: com.wenjay.sample.*.model.*.enums
  # 关闭MP3.0自带的banner
  banner: false
  global-config:
    #刷新mapper 调试神器
    refresh: true
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ASSIGN_ID:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ASSIGN_ID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    cache-enabled: true

#请求方式
#/doc.html
swagger:
  title: Wenjay-API接口定义说明
  license: Powered By Wenjay
  licenseUrl: https://www.wenjay.com/
  terms-of-service-url: https://www.wenjay.com/
  contact:
    email: wenjay@gmail.com
    url: https://www.wenjay.com/about.html


#Hystrix与Feign参数配置、请求处理的超时时间(Feign优于Ribbon的超时配置)
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000

feign: #feign的配置
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s
# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.
#隔离策略，默认是Thread,可选Thread｜Semaphore。thread用于线程池的隔离，一般适用于同步请求。semaphore是信号量模式，适用于异步请求
hystrix:
  command:
    default:
      fallback:
        enabled: true #当执行失败（run方法抛异常）或者请求被拒绝（资源不足）会尝试调用Fallback，默认true
      execution:
        isolation:
          #THREAD: 在单独的线程上执行，并发请求受线程池中的线程数限制
          #SEMAPHORE: 在调用线程上执行，并发请求量受信号量计数限制
          strategy: SEMAPHORE # THREAD｜SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true

# 配置服务监控
management:
  endpoints:
    web:
      exposure:
        include: '*'  #开放所有页面节点 ，默认只开启了health、info两个节点
  endpoint:
    info:
      enabled: true
    health:
      show-details: always #显示健康具体信息，默认不会显示详细信息
