version: '3'
services:
  fdfs-tracker:
    image: delron/fastdfs:latest
    container_name: fdfs-tracker
    hostname: fdfs-tracker
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/tracker/data:/var/fdfs
    ports:
      - 22122:22122
    command: tracker
    networks:
      - mynet
  fdfs-storage:
    image: delron/fastdfs:latest
    container_name: fdfs-storage
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/storage:/var/fdfs
    ports:
      - 23000:23000
      - 8888:8888
    environment:
      TRACKER_SERVER: "fdfs-tracker:22122"
    command: storage
    networks:
      - mynet
    depends_on:
      - fdfs-tracker
  fdfs-nginx:
    image: delron/fastdfs:latest
    container_name: fdfs-nginx
    environment:
      TRACKER_SERVER: "fdfs-tracker:22122"
    command: nginx
    ports:
      - 8088:8088
    networks:
      - mynet
    depends_on:
      - fdfs-storage
networks:
  mynet:
    external: false
