
# App服务配置
spring:
  redis:
    host: wenjay.redis
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://wenjay.mysql:3306/dxz_platform_demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&tinyInt1isBit=false

dxz:
  web:
    language:
      type: redis #redis, session, cookie, header 默认session
    filter:
      xssEnabled: false
      corsEnabled: false
  redis:
    client:
      type: lettuce  #默认：redisson lettuce
